name: 'Setup premake'
description: 'Install premake'
inputs:
  version:
    description: 'Premake version'
    required: true
branding:
  icon: 'box'
  color: 'red'
runs:
  using: 'node12'
  main: 'index.js'
