name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    
    - name: Setup premake
      uses: ./
      with:
        version: 5.0.0-beta1

    - run: premake5 --version
